### ISSUE TITLE
Consider Page Size 

### ISSUE THREAD

**Issue by derschiw** [plantagoIT/strapi-drag-drop-content-type-plugin#9]
hi, i have same issue. i use patch-package add another parameters to query like this

+ add code after `const contentTypePath = paths[paths.length - 1]`
 `const urlParams = new URLSearchParams(queryString);`
 `const pageSize = (urlParams.has('pageSize') ? urlParams.get('pageSize') : 100);`
 `const locale = (urlParams.has('plugins[i18n][locale]') ? urlParams.get('plugins[i18n][locale]') : '');`

+ replace code
`const { data } = await axiosInstance.get(`
 - `/content-manager/collection-types/${contentTypePath}?pageSize=${pageSize}&sort=rank:asc&locale=${locale}`

and enable localization for rank field

*** pageSize params use for get data from another page, because now query can get sort only page 1 and max 10 items

This plugin work fine for me.

Thank you

_Originally posted by @captainkie in https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/issues/7#issuecomment-1291739355_

**Comment by derschiw** [comment]
@captainkie I'm not sure if the page rank would be a good feature, since it would prevent users from beeing able to sort entries across pages. Though for very long list, it might be useful to somehow prevent fetching ALL entries --> suggestions?

**Comment by jpizzle34** [comment]
Hi @derschiw :wave: 

I think, in order to be scalable for a large number of entries, the sorting UI should only show the entries on the current page (i.e it mirrors the current page size of the content-manager). So I believe the page rank feature would be good to have.

A possible solution to the problem of sorting across page boundaries is to include the `pageSize + 1`th and `pageSize - 1`th entry in the sorting UI, so users can move an entry to the next page or previous page.

Another solution, is to add a pagination component to the sorting UI. The pagination component would be the similar to the existing pagination component of the content-manager. It would be operated by dragging and hovering over the `Next Page` or `Prev Page` button. This would trigger fetching the next/prev page of entries.

Also here's another idea which is a variation on the previous solution: Replace the pagination component with an "infinite scroll" mechanism. There can be drag and hover areas at the top and bottom of the sorting UI for the user to load the next/prev page entries. I think this would be the most ideal UX as the user can move entries between pages more fluidly. The user can also scroll to move between pages.

I don't know the codebase very well, so I'm not sure how feasible the last two solutions are. Would like to hear anyone's thoughts. I'm also happy to contribute in any way once I'm familiar with this plugin's codebase and the Strapi v4 codebase. :smiley:

**Comment by derschiw** [comment]
Hey thanks for your ideas

I agree that the "infinite scroll" idea would probably have the best UX, so I would go for this one. 

However I right now don't have time to implement this, I'm sorry!! Maybe during the next weeks it'll be better..

**Comment by jpizzle34** [comment]
No worries, I'm happy to have a look at it. I'll post back here if make any progress. :)

**Comment by derschiw** [comment]
In 310b5de98b1c21b89425a681c630cd5902e0743a I implemented a button that enables you to load more entries from neighbouring pages. It's not the best but a reasonable UX I think :)

**Comment by jpizzle34** [comment]
> In [310b5de](https://github.com/plantagoIT/strapi-drag-drop-content-type-plugin/commit/310b5de98b1c21b89425a681c630cd5902e0743a) I implemented a button that enables you to load more entries from neighbouring pages. It's not the best but a reasonable UX I think :)

Nice one! Just had a play around with it and it works great! Loading half the current Content Manager page size is a good choice. I agree, it's a good solution for an MVP and can be improved at a later stage. I was a looking at implementing infinite-scroll the other day and it looks high-effort for little gain, so I'll look at that at some other time.

Would be nice to have a another button for loading more previous entries in the case of a user starting on a 'middle' page.

**Comment by derschiw** [comment]
>  it looks high-effort for little gain, so I'll look at that at some other time.

Yes i agree

> Would be nice to have a another button for loading more previous entries in the case of a user starting on a 'middle' page.

Yes this would be nicer. I'll make an issue for now
